export const MYSTERIES_ACTION = {
  ADD_ITEM: 'mysteries/ADD_ITEM',
  SET_ITEM: 'mysteries/SET_ITEM',
  SET_ITEMS: 'mysteries/SET_ITEMS',
  UPDATE_ITEM: 'mysteries/UPDATE_ITEM',
  DELETE_ITEM: 'mysteries/DELETE_ITEM',
  SET_ITEMS_LOADING: 'mysteries/SET_ITEMS_LOADING',
  SET_DATASOURCE: 'mysteries/SET_DATASOURCE',
  UPSERT_DATASOURCE: 'mysteries/UPSERT_DATASOURCE',
  DELETE_DATASOURCE: 'mysteries/DELETE_DATASOURCE',
  CLEAR_DATASOURCE: 'mysteries/CLEAR_DATASOURCE',
  SET_DATASOURCE_LOADING: 'mysteries/SET_DATASOURCE_LOADING',
  CLEAR_ALL: 'mysteries/CLEAR_ALL',
}
